//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class pinforpricedb
{
    public int ID { get; set; }
    public double Price { get; set; }
    public int Votes_TooHigh { get; set; }
    public int Votes_TooLow { get; set; }
    public string Pinterest_ID { get; set; }
}
